In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

data = pd.read_csv('C:/Users/natha/Desktop/GitRepo/NathanLamplough/Data/Iris.csv', delimiter = ',', quoting = 3 )
x = data.drop(['Species','Id'], axis = 1)
x[:10]

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2
5            5.4           3.9            1.7           0.4
6            4.6           3.4            1.4           0.3
7            5.0           3.4            1.5           0.2
8            4.4           2.9            1.4           0.2
9            4.9           3.1            1.5           0.1

In [2]:
dimensions = len(x.columns)
x_data = np.asarray(x)
def input_fn():
    return tf.train.limit_epochs(tf.convert_to_tensor(x_data, dtype = tf.float32), num_epochs =1)

In [3]:
num_clusters = 4
kmeans = tf.contrib.factorization.KMeansClustering(num_clusters=num_clusters, use_mini_batch = False)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\natha\\AppData\\Local\\Temp\\tmpgzfyot34', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x000001D0F92DDBE0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [4]:
#training
num_iterations = 10
previous_centres = None

for i in range(num_iterations):
    kmeans.train(input_fn)
    cluster_centres = kmeans.cluster_centers()
    if previous_centres is not None:
        print('delta:', cluster_centres - previous_centres)
    previous_centres = cluster_centres
    print('score:', kmeans.score(input_fn))
print('cluster centres:', cluster_centres)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\natha\AppData\Local\Temp\tmpgzfyot34\model.ckpt.
INFO:tensorflow:Saving checkpoints for 1 into C:\Users\natha\AppData\Local\Temp\tmpgzfyot34\model.ckpt.
INFO:tensorflow:Loss for final step: None.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-23-16:11:04
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\natha\AppData\Local\Temp\tmpgzfyot34\model.ckpt-1
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:ten

INFO:tensorflow:Loss for final step: 71.74953.
delta: [[-0.03069496 -0.00699735 -0.0356822  -0.00459063]
 [-0.00733328 -0.01633334  0.00833344  0.00883332]
 [-0.01400042 -0.0059998  -0.01046157 -0.01153846]
 [-0.02428532 -0.01488733 -0.04932308 -0.04609013]]
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-01-23-16:11:14
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\natha\AppData\Local\Temp\tmpgzfyot34\model.ckpt-11
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1/1]
INFO:tensorflow:Finished evaluation at 2019-01-23-16:11:15
INFO:tensorflow:Saving dict for global step 11: global_step = 11, loss = 71.359795, score = 71.359795
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 11: C:\Users\natha\AppData\Local\Temp\tmpgzfyot34\model.ckpt-11
score: 71.359795
INFO:tensorflow:Calling model_fn.
INFO:tensorfl